# å…¨å±€é…ç½®
---
spring:
  application.name: gogo
...

# HTTPå®¢æˆ·ç«¯è®¾ç½®
---
http.client:
  #æœ€å¤§è¿æ¥æ•°
  maxTotal: 40
  #å¹¶å‘æ•°
  defaultMaxPerRoute: 20
  #åˆ›å»ºè¿æ¥çš„æœ€é•¿æ—¶é—´
  connectTimeout: 1000
  #ä»è¿æ¥æ± ä¸­è·å–åˆ°è¿æ¥çš„æœ€é•¿æ—¶é—´
  connectionRequestTimeout: 500
  #æ•°æ®ä¼ è¾“çš„æœ€é•¿æ—¶é—´
  socketTimeout: 500
...

# Gogoé…ç½®
---
gogo:
  # ç›‘å¬ç«¯å£
  port: 4999
  # æ—¥é—´æ¨¡å¼å¼€å§‹æ—¶é—´
  day-mode-start-time-string: "07:00"
  # æ—¥é—´æ¨¡å¼ç»“æŸæ—¶é—´
  day-mode-end-time-string: "19:00"
  # é¦–é¡µæ ‡è¯­
  slogan: æ¬¢è¿<a href="https://github.com/zenuo/gogo">star</a>ï¼ŒèŸ¹èŸ¹æ”¯æŒğŸ¥³
  # æœç´¢ç»“æœæ›¿æ¢è§„åˆ™
  substitute:
    - https://zh.wikipedia.org#https://176.122.157.73:3457
...